---
title: "Counting networks with given degrees"
description: "Tricks for counting types of networks, and why that's useful"
categories:
  - Paper explainer
  - Combinatorics
date: last-modified
---

- Release this once the paper on the symmetric estimate is out, since this is then a cornerstone of lots of other network modeling that I need to do.

This in an informal presentation of [this paper](https://doi.org/10.1098/rspa.2023.0470) done in collaboration with Alec Kirkley and Mark Newman. 

## Why count matrices?

In this paper we are interested in estimating the number of matrices that consist of non-negative integers and 

- Make a picture of what the question is. 
- Explain the importance of answering these types of combinatorial questions to creating microcanonical network models. 
- Make a figure of both the symmetric and asymmetric cases, and what they correspond to. 

## Estimating the number of matrices

- Should make a figure that schematically shows what is going on in the moment matching process 

## Numerically counting matrices

- Sequential importance sampling
- Describe as a dynamic programming strategy

