graph [
  directed 0
  compiledBy "Max Jerdee"
  licenseId "NOASSERTION"
  note "modularity_community: a name for each `group`, which is a community of the co-appearance network and NOT something Knuth recorded -- the Stanford GraphBase data has characters and chapter co-appearances only. Every group nonetheless falls exactly on a circle of the novel, so each gets a short name for it. For a grouping taken from the data rather than interpreted, see `volume`: Knuth records every encounter by chapter and his chapter labels are volume.book.chapter, so each character is placed in the volume they appear in most, under Hugo's own volume titles. Named modularity_community rather than modularity_group because the latter is the Analysis panel's own default output field, and running Louvain would overwrite these."
  author "Donald E. Knuth"
  source "https://www-cs-faculty.stanford.edu/~knuth/sgb.html"
  layout "force"
  colorAttr "modularity_community"
  sizeAttr "degree"
  labelAttr "label"
  edgeWidth "weight"
  edgeScale 2.4
  edgeOpacity 0.7
  title "Les Mis&#233;rables"
  sublabel "58 nodes &#183; weighted"
  category "Social"
  order 3
  keyNodeShort "Character"
  keyNodeFull "Character in Les Mis&#233;rables, colored by narrative group"
  keyEdgeShort "Co-appearance"
  keyEdgeFull "Two characters appear together in a scene, width &#8733; number of shared scenes"
  keyStyle "graphical"
  sizeScale 2.0
  node [ id 0  label "Myriel"        group "0"   x 399.87  y 69.23  modularity_community "Digne"  volume "Fantine" ]
  node [ id 1  label "Napoleon"      group "0"   x 410.48  y -64.9  modularity_community "Digne"  volume "Cosette" ]
  node [ id 2  label "Baptistine"    group "0"   x 391.19  y 132.24  modularity_community "Digne"  volume "Fantine" ]
  node [ id 3  label "Magloire"      group "0"   x 341.91  y 166.15  modularity_community "Digne"  volume "Fantine" ]
  node [ id 4  label "Geborand"      group "0"   x 363.43  y -32.26  modularity_community "Digne"  volume "Fantine" ]
  node [ id 5  label "Champtercier"  group "0"   x 415.21  y -7.81  modularity_community "Digne"  volume "Fantine" ]
  node [ id 6  label "Cravatte"      group "0"   x 474.31  y 15.53  modularity_community "Digne"  volume "Fantine" ]
  node [ id 7  label "Count"         group "0"   x 320.34  y 5.45  modularity_community "Digne"  volume "Fantine" ]
  node [ id 8  label "OldMan"        group "0"   x 462.27  y -40.46  modularity_community "Digne"  volume "Fantine" ]
  node [ id 9  label "Valjean"       group "1"   x 391.37  y 243.35  modularity_community "The law"  volume "Fantine" ]
  node [ id 10 label "Marguerite"    group "1"   x 338.06  y 107.74  modularity_community "The law"  volume "Fantine" ]
  node [ id 11 label "Isabeau"       group "1"   x 526.7  y 220.2  modularity_community "The law"  volume "Fantine" ]
  node [ id 12 label "Gervais"       group "1"   x 422.61  y 338.35  modularity_community "The law"  volume "Fantine" ]
  node [ id 13 label "Javert"        group "1"   x 308.97  y 290.13  modularity_community "The law"  volume "Fantine" ]
  node [ id 14 label "Fantine"       group "2"   x 560.01  y 317.55  modularity_community "Fantine"  volume "Fantine" ]
  node [ id 15 label "Tholomyes"     group "2"   x 626.86  y 308.87  modularity_community "Fantine"  volume "Fantine" ]
  node [ id 16 label "Listolier"     group "2"   x 666.9  y 359.93  modularity_community "Fantine"  volume "Fantine" ]
  node [ id 17 label "Fameuil"       group "2"   x 706.99  y 411  modularity_community "Fantine"  volume "Fantine" ]
  node [ id 18 label "Blacheville"   group "2"   x 602.75  y 369.67  modularity_community "Fantine"  volume "Fantine" ]
  node [ id 19 label "Favourite"     group "2"   x 731.17  y 350.79  modularity_community "Fantine"  volume "Fantine" ]
  node [ id 20 label "Dahlia"        group "2"   x 642.84  y 420.71  modularity_community "Fantine"  volume "Fantine" ]
  node [ id 21 label "Zephine"       group "2"   x 691.12  y 299.72  modularity_community "Fantine"  volume "Fantine" ]
  node [ id 22 label "Bamatabois"    group "1"   x 508.88  y 276.63  modularity_community "The law"  volume "Fantine" ]
  node [ id 23 label "Perpetue"      group "2"   x 645.02  y 250.54  modularity_community "Fantine"  volume "Fantine" ]
  node [ id 24 label "Simplice"      group "2"   x 486.94  y 333.89  modularity_community "Fantine"  volume "Fantine" ]
  node [ id 25 label "Judge"         group "1"   x 467.1  y 230.37  modularity_community "The law"  volume "Fantine" ]
  node [ id 26 label "Champmathieu"  group "1"   x 491  y 171.42  modularity_community "The law"  volume "Fantine" ]
  node [ id 27 label "Brevet"        group "1"   x 553.79  y 166.85  modularity_community "The law"  volume "Fantine" ]
  node [ id 28 label "Chenildieu"    group "1"   x 428.68  y 180.42  modularity_community "The law"  volume "Fantine" ]
  node [ id 29 label "Cochepaille"   group "1"   x 451.45  y 122.38  modularity_community "The law"  volume "Fantine" ]
  node [ id 30 label "Pontmercy"     group "4"   x 256.45  y 124.13  modularity_community "Gillenormand"  volume "Marius" ]
  node [ id 31 label "Cosette"       group "3"   x 298.56  y 230.6  modularity_community "Thenardiers"  volume "Cosette" ]
  node [ id 32 label "Thenardier"    group "3"   x 273.16  y 345.37  modularity_community "Thenardiers"  volume "Marius" ]
  node [ id 33 label "MmeThen."      group "3"   x 346.2  y 337.71  modularity_community "Thenardiers"  volume "Marius" ]
  node [ id 34 label "Eponine"       group "3"   x 248.28  y 283.39  modularity_community "Thenardiers"  volume "Saint-Denis" ]
  node [ id 35 label "Anzelma"       group "3"   x 315.3  y 416.76  modularity_community "Thenardiers"  volume "Cosette" ]
  node [ id 36 label "Gavroche"      group "3"   x 178.49  y 288.02  modularity_community "Thenardiers"  volume "Saint-Denis" ]
  node [ id 37 label "Mabeuf"        group "4"   x 215.74  y 230.24  modularity_community "Gillenormand"  volume "Saint-Denis" ]
  node [ id 38 label "Enjolras"      group "5"   x 106.46  y 275.62  modularity_community "Les Amis"  volume "Jean Valjean" ]
  node [ id 39 label "Combeferre"    group "5"   x -28.8  y 260.98  modularity_community "Les Amis"  volume "Saint-Denis" ]
  node [ id 40 label "Prouvaire"     group "5"   x 63.22  y 329.01  modularity_community "Les Amis"  volume "Saint-Denis" ]
  node [ id 41 label "Feuilly"       group "5"   x 38.41  y 266.36  modularity_community "Les Amis"  volume "Saint-Denis" ]
  node [ id 42 label "Courfeyrac"    group "5"   x 149.96  y 219.28  modularity_community "Les Amis"  volume "Saint-Denis" ]
  node [ id 43 label "Bahorel"       group "5"   x 9.53  y 203.97  modularity_community "Les Amis"  volume "Saint-Denis" ]
  node [ id 44 label "Bossuet"       group "5"   x 120.3  y 154.44  modularity_community "Les Amis"  volume "Saint-Denis" ]
  node [ id 45 label "Joly"          group "5"   x 79.19  y 211.13  modularity_community "Les Amis"  volume "Saint-Denis" ]
  node [ id 46 label "Grantaire"     group "5"   x 50.59  y 147.27  modularity_community "Les Amis"  volume "Saint-Denis" ]
  node [ id 47 label "Marius"        group "4"   x 188.72  y 161  modularity_community "Gillenormand"  volume "Marius" ]
  node [ id 48 label "Gillenormand"  group "4"   x 250.69  y 181.74  modularity_community "Gillenormand"  volume "Marius" ]
  node [ id 49 label "MlleGillen."   group "4"   x 203.87  y 99.86  modularity_community "Gillenormand"  volume "Marius" ]
  node [ id 50 label "Fauchelevent"  group "0"   x 510.7  y 114.25  modularity_community "Digne"  volume "Cosette" ]
  node [ id 51 label "Toussaint"     group "1"   x 450.9  y 288.57  modularity_community "The law"  volume "Saint-Denis" ]
  node [ id 52 label "Gueulemer"     group "3"   x 243.08  y 404.72  modularity_community "Thenardiers"  volume "Marius" ]
  node [ id 53 label "Babet"         group "3"   x 194.95  y 444.4  modularity_community "Thenardiers"  volume "Marius" ]
  node [ id 54 label "Claquesous"    group "3"   x 253.36  y 466.22  modularity_community "Thenardiers"  volume "Marius" ]
  node [ id 55 label "Montparnasse"  group "3"   x 206.14  y 352.93  modularity_community "Thenardiers"  volume "Saint-Denis" ]
  node [ id 56 label "Brujon"        group "3"   x 156.88  y 394.21  modularity_community "Thenardiers"  volume "Saint-Denis" ]
  node [ id 57 label "MmeHucheloup"  group "5"   x 91.26  y 94.26  modularity_community "Les Amis"  volume "Saint-Denis" ]
  edge [ source 1  target 0  weight 1  ]
  edge [ source 2  target 0  weight 8  ]
  edge [ source 3  target 0  weight 10 ]
  edge [ source 3  target 2  weight 6  ]
  edge [ source 4  target 0  weight 1  ]
  edge [ source 5  target 0  weight 1  ]
  edge [ source 6  target 0  weight 1  ]
  edge [ source 7  target 0  weight 2  ]
  edge [ source 8  target 0  weight 1  ]
  edge [ source 9  target 3  weight 3  ]
  edge [ source 9  target 2  weight 3  ]
  edge [ source 9  target 0  weight 5  ]
  edge [ source 9  target 13 weight 1  ]
  edge [ source 9  target 14 weight 3  ]
  edge [ source 9  target 31 weight 1  ]
  edge [ source 9  target 32 weight 1  ]
  edge [ source 9  target 33 weight 1  ]
  edge [ source 9  target 22 weight 1  ]
  edge [ source 9  target 36 weight 1  ]
  edge [ source 9  target 51 weight 1  ]
  edge [ source 10 target 9  weight 1  ]
  edge [ source 11 target 9  weight 1  ]
  edge [ source 12 target 9  weight 1  ]
  edge [ source 15 target 14 weight 3  ]
  edge [ source 16 target 14 weight 3  ]
  edge [ source 16 target 15 weight 4  ]
  edge [ source 17 target 14 weight 3  ]
  edge [ source 17 target 15 weight 4  ]
  edge [ source 17 target 16 weight 4  ]
  edge [ source 18 target 14 weight 3  ]
  edge [ source 18 target 15 weight 4  ]
  edge [ source 18 target 16 weight 4  ]
  edge [ source 18 target 17 weight 4  ]
  edge [ source 19 target 14 weight 3  ]
  edge [ source 19 target 15 weight 3  ]
  edge [ source 19 target 16 weight 3  ]
  edge [ source 19 target 17 weight 3  ]
  edge [ source 19 target 18 weight 3  ]
  edge [ source 20 target 14 weight 3  ]
  edge [ source 20 target 15 weight 3  ]
  edge [ source 20 target 16 weight 3  ]
  edge [ source 20 target 17 weight 3  ]
  edge [ source 20 target 18 weight 3  ]
  edge [ source 20 target 19 weight 3  ]
  edge [ source 21 target 14 weight 3  ]
  edge [ source 21 target 15 weight 3  ]
  edge [ source 21 target 16 weight 3  ]
  edge [ source 21 target 17 weight 3  ]
  edge [ source 21 target 18 weight 3  ]
  edge [ source 21 target 19 weight 3  ]
  edge [ source 21 target 20 weight 3  ]
  edge [ source 22 target 14 weight 1  ]
  edge [ source 23 target 14 weight 1  ]
  edge [ source 24 target 14 weight 1  ]
  edge [ source 24 target 9  weight 2  ]
  edge [ source 25 target 9  weight 3  ]
  edge [ source 25 target 22 weight 2  ]
  edge [ source 26 target 9  weight 3  ]
  edge [ source 26 target 25 weight 3  ]
  edge [ source 26 target 22 weight 2  ]
  edge [ source 27 target 9  weight 2  ]
  edge [ source 27 target 26 weight 2  ]
  edge [ source 27 target 25 weight 2  ]
  edge [ source 28 target 9  weight 2  ]
  edge [ source 28 target 26 weight 2  ]
  edge [ source 28 target 25 weight 2  ]
  edge [ source 28 target 27 weight 2  ]
  edge [ source 29 target 9  weight 2  ]
  edge [ source 29 target 26 weight 2  ]
  edge [ source 29 target 25 weight 2  ]
  edge [ source 29 target 27 weight 2  ]
  edge [ source 29 target 28 weight 2  ]
  edge [ source 30 target 47 weight 6  ]
  edge [ source 31 target 9  weight 1  ]
  edge [ source 31 target 32 weight 4  ]
  edge [ source 31 target 33 weight 4  ]
  edge [ source 31 target 47 weight 1  ]
  edge [ source 32 target 33 weight 13 ]
  edge [ source 32 target 34 weight 2  ]
  edge [ source 32 target 35 weight 2  ]
  edge [ source 32 target 36 weight 1  ]
  edge [ source 32 target 52 weight 1  ]
  edge [ source 32 target 53 weight 1  ]
  edge [ source 32 target 54 weight 1  ]
  edge [ source 32 target 55 weight 1  ]
  edge [ source 32 target 56 weight 1  ]
  edge [ source 33 target 34 weight 1  ]
  edge [ source 33 target 35 weight 1  ]
  edge [ source 34 target 36 weight 2  ]
  edge [ source 34 target 47 weight 3  ]
  edge [ source 34 target 42 weight 1  ]
  edge [ source 36 target 13 weight 1  ]
  edge [ source 36 target 37 weight 1  ]
  edge [ source 36 target 38 weight 1  ]
  edge [ source 36 target 39 weight 1  ]
  edge [ source 36 target 40 weight 1  ]
  edge [ source 36 target 41 weight 1  ]
  edge [ source 36 target 42 weight 2  ]
  edge [ source 36 target 43 weight 1  ]
  edge [ source 36 target 44 weight 1  ]
  edge [ source 36 target 45 weight 1  ]
  edge [ source 36 target 46 weight 1  ]
  edge [ source 36 target 56 weight 1  ]
  edge [ source 37 target 38 weight 1  ]
  edge [ source 37 target 42 weight 1  ]
  edge [ source 37 target 43 weight 1  ]
  edge [ source 38 target 39 weight 6  ]
  edge [ source 38 target 40 weight 3  ]
  edge [ source 38 target 41 weight 3  ]
  edge [ source 38 target 42 weight 6  ]
  edge [ source 38 target 43 weight 3  ]
  edge [ source 38 target 44 weight 3  ]
  edge [ source 38 target 45 weight 3  ]
  edge [ source 38 target 46 weight 3  ]
  edge [ source 39 target 40 weight 3  ]
  edge [ source 39 target 41 weight 3  ]
  edge [ source 39 target 42 weight 3  ]
  edge [ source 39 target 43 weight 3  ]
  edge [ source 39 target 44 weight 3  ]
  edge [ source 39 target 45 weight 3  ]
  edge [ source 39 target 46 weight 3  ]
  edge [ source 40 target 41 weight 3  ]
  edge [ source 40 target 42 weight 3  ]
  edge [ source 40 target 43 weight 3  ]
  edge [ source 40 target 44 weight 3  ]
  edge [ source 40 target 45 weight 3  ]
  edge [ source 40 target 46 weight 3  ]
  edge [ source 41 target 42 weight 3  ]
  edge [ source 41 target 43 weight 3  ]
  edge [ source 41 target 44 weight 3  ]
  edge [ source 41 target 45 weight 3  ]
  edge [ source 41 target 46 weight 3  ]
  edge [ source 42 target 43 weight 3  ]
  edge [ source 42 target 44 weight 3  ]
  edge [ source 42 target 45 weight 3  ]
  edge [ source 42 target 46 weight 3  ]
  edge [ source 43 target 44 weight 3  ]
  edge [ source 43 target 45 weight 3  ]
  edge [ source 43 target 46 weight 3  ]
  edge [ source 44 target 45 weight 5  ]
  edge [ source 44 target 46 weight 4  ]
  edge [ source 45 target 46 weight 4  ]
  edge [ source 46 target 57 weight 2  ]
  edge [ source 47 target 42 weight 6  ]
  edge [ source 47 target 44 weight 5  ]
  edge [ source 47 target 45 weight 5  ]
  edge [ source 47 target 46 weight 4  ]
  edge [ source 48 target 47 weight 2  ]
  edge [ source 48 target 49 weight 9  ]
  edge [ source 49 target 47 weight 6  ]
  edge [ source 50 target 9  weight 1  ]
  edge [ source 52 target 53 weight 1  ]
  edge [ source 52 target 54 weight 1  ]
  edge [ source 52 target 55 weight 1  ]
  edge [ source 53 target 54 weight 1  ]
  edge [ source 53 target 55 weight 1  ]
  edge [ source 54 target 55 weight 1  ]
  edge [ source 55 target 34 weight 1  ]
  edge [ source 55 target 36 weight 1  ]
  edge [ source 56 target 52 weight 1  ]
  edge [ source 56 target 53 weight 1  ]
  edge [ source 56 target 54 weight 1  ]
  edge [ source 56 target 55 weight 1  ]
  edge [ source 57 target 38 weight 1  ]
  edge [ source 57 target 42 weight 1  ]
  edge [ source 57 target 43 weight 1  ]
  edge [ source 57 target 44 weight 1  ]
  edge [ source 57 target 45 weight 1  ]
]
