project:
  type: website
  output-dir: ../docs

website:
  title: "Max Jerdee"
  favicon: assets/images/icon.svg
  navbar:
    left:
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: demos.qmd
        text: Demos
      - href: blog.qmd
        text: Blog
      - href: cv.qmd
        text: CV

  
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: Demos
        auto: demos

      - section: Blog
        auto: blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



