project:
  type: website
  output-dir: ../docs

website:
  title: "Max Jerdee"
  favicon: assets/images/icon.svg
  navbar:
    left:
      - href: research.qmd
        text: Research
      - href: papers.qmd
        text: Papers
      - href: demos.qmd
        text: Demos
      - href: blog.qmd
        text: Blog
      - href: CV.qmd
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



