project:
  type: website
  output-dir: ../docs
  resources:
  - "./assets"
  - "./demos_code"

website:
  title: "Max Jerdee"
  favicon: assets/images/icon.svg
  google-analytics: "G-SY1YC6MMLM"
  navbar:
    left:
      - href: research.qmd
        text: Research
      - href: papers.qmd
        text: Papers
      - href: code.qmd
        text: Code
      - href: demos.qmd
        text: Demos
      - href: notes.qmd
        text: Notes
      - href: assets/pdf/CV.pdf
        text: CV

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



